name: Scraper Automático

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y unzip curl

      - name: Instalar ChromeDriver compatível
        run: |
          # Baixar versão compatível com Chrome 135
          curl -O https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

          # Verificar versões instaladas
          google-chrome --version || true
          chromedriver --version || true

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Executar o scraper
        run: python scraper.py
